### ISSUE TITLE
graph export - 0KB Files

### ISSUE THREAD

**Issue by SeameX** [ltearno/pom-explorer#22]
Hello,

pom explorer looks very interesting. Unfortunately the graph export is not working for me. 

i imported a lot of projects 40+. With "graph" i can view all the projects correct.
When i do "graph export" im getting two file links for graphml files. Both files are empty.

Best regards

Stefan

**Comment by ltearno** [comment]
Should be fixed now, can you confirm please ?

**Comment by SeameX** [comment]
nope not working with latest master.

**Comment by SeameX** [comment]
Ping still not working.

**Comment by ltearno** [comment]
Sorry I did not have time to go into your problem.
After having done the export, you can search directly in the pom explorer
sub directories for  .graphml files. Are they empty too?
I will investigate that more when I come back from Java One (that's why I
didn't have time to fix your problem, I had to prepare my presentation
there, sorry...)

**Comment by SeameX** [comment]
No Problem ;)

yes files are there.

http://localhost:8090/files/graph-session-1049217670-1473089295397.graphml
pom-explorer\served-data\graph-session-1049217670-1473089295397.graphml

**Comment by ltearno** [comment]
Are they empty on the file system?

**Comment by SeameX** [comment]
Nope they are not empty but they just got the data from my last comment nothing more. So no "project" data at all.

**Comment by SeameX** [comment]
No worries im on holiday for the next 2 weeks ;)
The pom files are corporate so i cant send them to you but i can try to help finding the bug.
