### ISSUE TITLE
Filter groups on the Graph

### ISSUE THREAD

**Issue by gauravlanjekar** [ltearno/pom-explorer#28]
Hi is there are way right now to do something what I could do to filter for specific groups 

for e.g. on maven dependency tree plugin i could do something like `mvn dependency:tree -Dincludes com.example`

**Comment by ltearno** [comment]
Do you mean the WebGL 3d Graph (graph command) or the exported GraphML data (graph export command) ?
For the WebGL 3d graph, you can do it like this by replacing the confirmNode function and clicking on the refresh button:

	confirmNode: function(gav) {
	  return gav.indexOf("com.example")==0;
	},

Can you please confirm that it is working for you so that i can close the issue ?
Thanks

**Comment by gauravlanjekar** [comment]
Well, What I actually meant was for the graph export.

**Comment by ltearno** [comment]
OK, so for the graph export, that would be a new functionality.

I often use the exported graphml with a tool like yEd, which might be able
to filter as you require.

Anyway, i don't close the issue as implementing it won't be difficult. When
I have some time, i will do it.

Thanks

Le jeu. 8 déc. 2016 à 14:05, Gaurav Lanjekar <notifications@github.com> a
écrit :

**Comment by ltearno** [comment]
It's now implemented ! you can do `graph export org.spring` for example to export a graph ml file with only gavs matching 'org.spring'

**Comment by gauravlanjekar** [comment]
Awesome !! Thanks
