### ISSUE TITLE
Command graph export 

### ISSUE THREAD

**Issue by marcelolucio1982** [ltearno/pom-explorer#8]
Dear,

The command "graph export" return Error ! : null. I download from master. 

Stacktrace:
![image](https://cloud.githubusercontent.com/assets/3787982/12170420/8da95446-b528-11e5-879a-497b8e08a110.png)

**Comment by ltearno** [comment]
Hi and thanks for your report. The target directory was not generated before trying to generate the export file.
So now this should work.

Can you confirm please ?

Also as a note, you may want to try the dev branch and provide with some feedback about the ui improvments. If you do, thanks a lot !!

**Comment by marcelolucio1982** [comment]
Hi ltearno,

The generate files (graphml) open incorret diagram
![image](https://cloud.githubusercontent.com/assets/3787982/12176365/5355eaa4-b54e-11e5-80fe-9ad8f7aacd71.png)

**Comment by ltearno** [comment]
Hi,

once you generate the graphml file and open it in yEd, you are not yet completely finished, because yEd needs to be instructed what it has to display from the graph data.

So once you have opened the graph file in yed, you can do the following :

Edit > Properties mapper...

Select the line in the table and click on the "Apply" button

Then select the "New configuration (Edge)" line on the left of the dialog box.

Click the first line in the table and click on the "Apply" button.

Then click OK to close the dialog box.

Now normally, all nodes are correctly presented in the yEd editor, the only remaining thing to do is to organize the nodes. You can do this by chicking on Layout > Hierarchical > OK.

You should then get something usable...

Please note that two files are generated when you use the "graph export" command. One is working at the maven project level (pom.xml files), and the other (with "repos" in the name) corresponds to git repositories dependencies, if your projects use git for version control.

Hope this helps you !

**Comment by marcelolucio1982** [comment]
Thanks ltearno!! Its work!!!
You know why the labels are not filled with name of the dependency

**Comment by ltearno** [comment]
With the instruction i gave you, i get a graph like this, with the labels filled with the name of the dependency.

![image](https://cloud.githubusercontent.com/assets/191069/12202504/87a81f84-b62a-11e5-8c31-4f24f5cf3f24.png)

Once again there is a file related to git repositories dependencies, which would not contain maven dependencies but aggregate them by repository. With this file, you don't have dependency name.

But if you use the file without "repo" in the name, you should definitely have the dependency names, as shown in the screenshot.

Maybe there is a point i didn't get correctly ?

**Comment by marcelolucio1982** [comment]
Without "repo" name the generate graph is:
![image](https://cloud.githubusercontent.com/assets/3787982/12203615/f7dc78a4-b616-11e5-9e7f-31c5bfc2811d.png)

Dependency names are "Vertex Label"

![image](https://cloud.githubusercontent.com/assets/3787982/12203646/26337482-b617-11e5-9ee0-2f5677fdc9d8.png)

**Comment by ltearno** [comment]
Could you please send me the graphml file ? So i can investigate in more
details ?
You can send it by email for privacy...
M'y email is ltearno@gmail.com

Thanks

Le ven. 8 janv. 2016 17:50, marcelolucio1982 <notifications@github.com> a
écrit :

**Comment by ltearno** [comment]
Please can you confim the issue is closed on your side ?

Thanks
