### ISSUE TITLE
missing classes

### ISSUE THREAD

**Issue by wimmon** [ltearno/pom-explorer#9]
Hello, 
I downloaded the zip file of the master branch but when importing it into my eclipse,
I have a few errors on not existing classes. They are not in the imports, so I assume they should be in the same package. Probably I missed something? Can you check this? Thank you.
Kr, Wim

missing classes "BuilderAutoThreaded " , MavenBuildTaskAutoThreaded , 
==Errors========

BuilderAutoThreaded cannot be resolved to a type	WorkingSession.java	/pom-explorer/src/main/java/fr/lteconsulting/pomexplorer	line 45	Java Problem
BuilderAutoThreaded cannot be resolved to a type	WorkingSession.java	/pom-explorer/src/main/java/fr/lteconsulting/pomexplorer	line 45	Java Problem
BuilderAutoThreaded cannot be resolved to a type	WorkingSession.java	/pom-explorer/src/main/java/fr/lteconsulting/pomexplorer	line 51	Java Problem
BuilderAutoThreaded cannot be resolved to a type	WorkingSession.java	/pom-explorer/src/main/java/fr/lteconsulting/pomexplorer	line 95	Java Problem
BuilderAutoThreaded cannot be resolved to a type	WorkingSession.java	/pom-explorer/src/main/java/fr/lteconsulting/pomexplorer	line 100	Java Problem
MavenBuildTaskAutoThreaded cannot be resolved to a type	Builder.java	/pom-explorer/src/main/java/fr/lteconsulting/pomexplorer	line 270	Java Problem
MavenBuildTaskAutoThreaded cannot be resolved to a type	Builder.java	/pom-explorer/src/main/java/fr/lteconsulting/pomexplorer	line 270	Java Problem
ProjectsWatcherAutoThreaded cannot be resolved to a type	WorkingSession.java	/pom-explorer/src/main/java/fr/lteconsulting/pomexplorer	line 43	Java Problem

**Comment by ltearno** [comment]
Hello,

Those files are generated on the fly through a Java processor.

The java processor is in the project fr.lteconsulting:autothreaded:1.0-SNAPSHOT which the pom file is located in the processor directory.

So first, this project should not be opened in Eclipse because if it is opened, Eclipse won't trigger the generator that is in this project (that's an eclipse limitation).

Then eclipse needs the jar from the authreaded project. For this to happen, two things must be done :

- you should build the authothreaded project locally because i did not push it yet on maven central. The easiest way to do that is to do a `mvn clean install` from the root directory of pom-explorer.
- if you don't have the **m2e-apt** connector installed yet, first install it. Instructions are found [here](https://github.com/jbosstools/m2e-apt).
- you should tell eclipse to enable annotation processing. For that go to Settings > Maven > Annotation Processing and choose one of the first two options (Automatically configure JDT or Experimental). This will enable annotation processing in Eclipse and the BuilderAutoThreaded class should be generated under the target/generated-sources/annotations directory.

So to resume :

- first do a mvn clean install in the project's root directory
- install and configure eclipse's m2e-apt connector
- it should work !

Here is a screenshot of the settings dialog :

![image](https://cloud.githubusercontent.com/assets/191069/12350853/d7cff7ee-bb79-11e5-8d21-7311d9ea105c.png)

And a screenshot of the project opened on Eclipse :

![image](https://cloud.githubusercontent.com/assets/191069/12350868/f6a65bb8-bb79-11e5-94be-cc0939f0739b.png)

**Comment by wimmon** [comment]
Hello Thanks for the answer. I succeeded to get it running. Now I can explore it :-)

**Comment by ltearno** [comment]
Cool !

If you have time, maybe you could try the dev branch and tell me what you think of the new UI (still in progress)
